In [4]:
import numpy as np

In [69]:
# Create an array python
my_list = [1, 2, 3]

In [6]:
# Create an array with numpy because the array numpy it is more efficient 
np.array(my_list)

array([1, 2, 3])

In [7]:
# Créate nested array
nested_list = [[1,2],[3,4],[5,6]]

In [9]:
# It is possible to work with a nested array
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
# giv array of int value (start, end, step) 
np.arange(0,10)
#np.arange(0,10,2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
# Creates array of 0 of 4 by 10 and if not spécified dtype is float
#np.zeros((4,10), dtype=int)
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
# Creates array of 1 of 4 by 10 and if not spécified dtype is float
#np.ones((4,10), dtype=int)
np.ones((4,10))

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [22]:
np.linspace(0,10,21)

array([ 0.,  5., 10.])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
np.random.rand(2)

array([0.67367906, 0.71422769])

In [40]:
np.random.rand(3,4)

array([[0.69062218, 0.3845468 , 0.15618702, 0.07230651],
       [0.34340103, 0.99716948, 0.20728466, 0.80759867],
       [0.32570909, 0.9358351 , 0.55036363, 0.50698087]])

In [41]:
np.random.randn(5,5)

array([[-0.51380354,  0.62737958,  0.95320731,  1.25696487,  1.52040186],
       [-1.16337262, -0.99384148,  1.64737699,  0.59021614, -2.13388518],
       [-0.26785031,  0.82646855, -0.44715448, -1.45011455,  2.03612492],
       [-0.38875363, -0.30900603,  1.2324148 , -0.96918607,  2.01849059],
       [ 0.04863798,  1.09802816,  0.48022164, -0.46665913, -0.50208237]])

In [44]:
#np.random.randint(1,100,10)
np.random.randint(1,100,(2,3))

array([[92, 74, 22],
       [89, 33, 58]])

In [47]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [48]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [51]:
arr = np.arange(25)

In [52]:
ranarr = np.random.randint(0,50,10)

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
ranarr

array([ 1, 20, 32, 11, 21, 43, 24, 48, 26, 41])

In [55]:
arr.shape

(25,)

In [59]:
arr = arr.reshape(5,5)

In [58]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
ranarr

array([ 1, 20, 32, 11, 21, 43, 24, 48, 26, 41])

In [61]:
ranarr.max()

48

In [62]:
ranarr.argmax()

7

In [63]:
ranarr.min()

1

In [64]:
ranarr.argmin()

0

In [65]:
ranarr.dtype

dtype('int32')

In [66]:
myarr = np.random.rand(4)

In [67]:
myarr

array([0.04666566, 0.97375552, 0.23277134, 0.09060643])

In [68]:
myarr.dtype

dtype('float64')