In [2]:
import numpy as np

In [3]:
# Create an array python
my_list = [1, 2, 3]

In [4]:
# Create an array with numpy because the array numpy it is more efficient 
np.array(my_list)

array([1, 2, 3])

In [5]:
# Créate nested array
nested_list = [[1,2],[3,4],[5,6]]

In [6]:
# It is possible to work with a nested array
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
# giv array of int value (start, end, step) 
np.arange(0,10)
#np.arange(0,10,2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# Creates array of 0 of 4 by 10 and if not spécified dtype is float
#np.zeros((4,10), dtype=int)
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
# Creates array of 1 of 4 by 10 and if not spécified dtype is float
#np.ones((4,10), dtype=int)
np.ones((4,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.random.rand(2)

array([0.5044007 , 0.52858651])

In [13]:
np.random.rand(3,4)

array([[0.71917599, 0.89204019, 0.52842732, 0.16441871],
       [0.34257827, 0.22325318, 0.62569156, 0.91788947],
       [0.6116792 , 0.20640147, 0.3235643 , 0.05679155]])

In [14]:
np.random.randn(5,5)

array([[ 2.68038694,  1.62982635,  1.14484072, -0.55749887,  1.32599191],
       [-0.26667715, -0.18016352, -1.16541376,  0.18209392, -0.68725588],
       [-0.30927015,  0.18263894, -0.96325548,  0.13785939, -0.53279461],
       [-1.97669034, -0.31128936,  0.44337606, -0.13465069,  0.20646173],
       [ 1.68661225, -0.18929102,  1.34925666,  0.26929481, -0.01873359]])

In [15]:
#np.random.randint(1,100,10)
np.random.randint(1,100,(2,3))

array([[45, 58, 77],
       [83, 31, 49]])

In [16]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [17]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [18]:
arr = np.arange(25)

In [19]:
ranarr = np.random.randint(0,50,10)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
ranarr

array([35, 39, 23,  2, 21,  1, 23, 43, 29, 37])

In [22]:
arr.shape

(25,)

In [23]:
arr = arr.reshape(5,5)

In [24]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
ranarr

array([35, 39, 23,  2, 21,  1, 23, 43, 29, 37])

In [26]:
ranarr.max()

43

In [27]:
ranarr.argmax()

7

In [28]:
ranarr.min()

1

In [29]:
ranarr.argmin()

5

In [30]:
ranarr.dtype

dtype('int32')

In [31]:
myarr = np.random.rand(4)

In [32]:
myarr

array([7.78765841e-04, 9.92211559e-01, 6.17481510e-01, 6.11653160e-01])

In [33]:
myarr.dtype

dtype('float64')